#!/usr/bin/env php
<?php

/*
 * This file is part of the sfHadoriThemePlugin package.
 * (c) Brent Shaffer <bshafs@gmail.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

chdir(dirname(__FILE__));
require_once(dirname(__FILE__).'/config/ProjectConfiguration.class.php');
include(sfCoreAutoload::getInstance()->getBaseDir().'/command/cli.php');
