<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * @property enum $gender
 * @property date $birthday
 * @property integer $company_id
 * @property Company $Company
 * @property Doctrine_Collection $Addresses
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getAddress()    Returns the current record's "address" value
 * @method enum                getGender()     Returns the current record's "gender" value
 * @method date                getBirthday()   Returns the current record's "birthday" value
 * @method integer             getCompanyId()  Returns the current record's "company_id" value
 * @method Company             getCompany()    Returns the current record's "Company" value
 * @method Doctrine_Collection getAddresses()  Returns the current record's "Addresses" collection
 * @method Contact             setName()       Sets the current record's "name" value
 * @method Contact             setAddress()    Sets the current record's "address" value
 * @method Contact             setGender()     Sets the current record's "gender" value
 * @method Contact             setBirthday()   Sets the current record's "birthday" value
 * @method Contact             setCompanyId()  Sets the current record's "company_id" value
 * @method Contact             setCompany()    Sets the current record's "Company" value
 * @method Contact             setAddresses()  Sets the current record's "Addresses" collection
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('gender', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Male',
              1 => 'Female',
             ),
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasMany('ContactAddress as Addresses', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}